modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="connectormod"
version="${file.jarVersion}"
displayName="Connector"
#logoFile="examplemod.png"
#credits="Thanks for this example mod goes to Java"
authors="Su5eD"
description='''
Connector.
'''
[[dependencies.connectormod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.connectormod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
