name: Mod Incompatibility
description: Report an incompatible mod
labels: [compat]
body:
  - type: markdown
    attributes:
      value: "## 👋 Welcome!"
  - type: markdown
    attributes:
      value: |
        ### 📋 Checklist
        Thank you for taking your time to report this bug!  
        Before reporting, please make ensure that:
        - You are using the **latest** available version of Connector and its dependencies
        - You've installed a **minimal set of mods** required to reproduce the issue. 
          Issues with modpacks and excessive amount of mods will *not* be accepted, as they take a long time to diagnose.
          Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.  
          If you're unsure which mods might be at fault, try using [binary search](https://www.reddit.com/r/feedthebeast/comments/evpy6r/tips_for_modpack_authors_how_to_find_misbehaving/) - removing half of installed mods
          repeatedly until the faulty mod is found.
  - type: input
    id: mod
    attributes: 
      label: Mod Name
      description: "Name of the problematic mod"
      placeholder: "Examplemod"
    validations:
      required: true
  - type: input
    id: homepage
    attributes: 
      label: Mod Homepage
      description: "A link to the mod's homepage. This can be its CurseForge, Modrinth, Github repository or something else."
      placeholder: "https://example.com"
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        How do you trigger this bug? Please walk us through it step by step.
        If applicable, add screenshots to help explain your problem. In case the mod crashes the game without
        ever loading, feel free to skip this step.
      value: |
        1.
        2.
        3.
        ...
  - type: input
    id: logs
    attributes:
      label: Logs
      description: |
        If applicable (crash, error output in console), please provide your debug.log **and** crash report.
        Otherwise, we recommend uploading the debug.log found in your `.minecraft/logs` directory.
        To upload logs, use an external paste site, such as [Github Gist](https://gist.github.com/) (recommended), [Ubuntu Pastebin](https://paste.ubuntu.com/) or [Pastebin](http://pastebin.com/)
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context about the problem here, such as your current environment or other mods that might be causing this bug."